### ISSUE TITLE
How do I set this up with jquery promises?

### ISSUE THREAD

**Issue by dschissler** [gaearon/promise-loader#3]
I want to use this with jquery promises as I see that jquery 3 coming out in the next several months will support Promise/A+ and its just one less dependency for me within an acceptable time frame for me.

I just need a two line loader config example and one line on how to call it.

**Comment by gaearon** [comment]
### `jQueryPromise.js`
``js
module.exports = require('jquery').Promise;
```

Then, when you need it, use

```js
var loadSomePage = require('promise?./jQueryPromise!./somePage');
loadSomePage().then(...);
```
